/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Edgar
 */
public class Menu extends javax.swing.JPanel {

    private JFrame frame;
    private String name;
    private JButton enter;
    private JTextField username = new JTextField();

    static {
        try {
            background = ImageIO.read(ClassLoader.getSystemClassLoader().getResourceAsStream("resources/img/menu_background.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private static Image background;

    /**
     * Creates new form Menu
     */
    public Menu(JFrame frame) {
        initComponents();
        enter = new JButton("Enter Game");
        this.frame = frame;
        setSize(475, 586);
        username.setBounds(getWidth() / 2 - 90, getHeight() / 2 - 30, 150, 30);
        enter.setBounds(getWidth() / 2 - 90, getHeight() / 2 + 10, 150, 30);
        username.setHorizontalAlignment(JTextField.CENTER);
        username.addActionListener(new MenuAction());
        enter.addActionListener(new MenuAction());
        add(username);
        add(enter);

        frame.setContentPane(this);
        frame.setSize(475, 586);
        frame.setVisible(true);

    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(background, 0, 0, getWidth(), getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void startGame() {
        final MainGame game = new MainGame(name);
        frame.setContentPane(game);
        frame.setSize(800, 600);
        WindowListener exitListener = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Exit");
                game.disconnect();
            }
        };

        frame.addWindowListener(exitListener);
        frame.revalidate();
        frame.repaint();
        game.requestFocus();
        
        new Thread(game).start();
    }

    private class MenuAction implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            name = username.getText();
            System.out.println("Entered " + name);
            //TODO CHECKS FOR NAME
            startGame();

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
